version: '3.8'

services:
  book_catalog:
    build: ./book_catalog
    container_name: book_catalog
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/bookdb
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app-network

  inventory_management:
    build: ./inventory_management
    container_name: inventory_management
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/inventorydb
    ports:
      - "8001:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
