# Your Solutionversion: '3'
services:
  book_catalog:
    build: ./book_catalog
    container_name: book_catalog
    ports:
      - "5000:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  inventory_management:
    build: ./inventory_management
    container_name: inventory_management
    ports:
      - "5001:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
