version: '3.8'

services:
  book_catalog:
    build:
      context: .
      dockerfile: Dockerfile.book_catalog
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "postgresql://book_catalog_n60i_user:8prUeK5Mdv7yg1bCAPb165m36uefjjmq@dpg-crclg63v2p9s73ci46hg-a.oregon-postgres.render.com/book_catalog_n60i"
    networks:
      - mynetwork

  inventory_management:
    build:
      context: .
      dockerfile: Dockerfile.inventory_management
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: "postgresql://book_catalog_n60i_user:8prUeK5Mdv7yg1bCAPb165m36uefjjmq@dpg-crclg63v2p9s73ci46hg-a.oregon-postgres.render.com/book_catalog_n60i"
    networks:
      - mynetwork

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: book_catalog_n60i_user
      POSTGRES_PASSWORD: 8prUeK5Mdv7yg1bCAPb165m36uefjjmq
      POSTGRES_DB: book_catalog_n60i
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
