version: '3'

services:

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: book_catalog_n60i_user
      POSTGRES_PASSWORD: 8prUeK5Mdv7yg1bCAPb165m36uefjjmq
      POSTGRES_DB: book_catalog_n60i
    restart: always

  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://book_catalog_n60i_user:8prUeK5Mdv7yg1bCAPb165m36uefjjmq@postgres-db:5432/book_catalog_n60i
    depends_on:
      - postgres
    restart: "no"

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://book_catalog_n60i_user:8prUeK5Mdv7yg1bCAPb165m36uefjjmq@postgres-db:5432/book_catalog_n60i
    depends_on:
      - postgres
    restart: "no"
